---
# Point of entry in the ansible Playbook

- name: Setup alaveteli and dependencies
  hosts: all
  pre_tasks:
  # pre_tasks will run before dependencies such as postgresql
    - name: Ensure a locale exists
      become: yes
      locale_gen:
        name: en_GB.UTF-8
        state: present

  roles:
    - alaveteli
